### ISSUE TITLE
Quick Share - another check after 10 seconds not blocked

### ISSUE THREAD

**Issue by AmaneDev** [Bananz0/GalaxyBookEnabler#1]
Hello,

thank you for your script, it helped me so much, just please fix issue when Quick Share closes after 10 seconds (non-Intel WiFi card), otherwise it works perfectly! ;)

**Comment by Bananz0** [comment]
Unfortunately I don't think i could currently do that. I will have a deeper look into that but at the moment, this isn't possible.
