### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by bakisama** [Bananz0/GalaxyBookEnabler#11]
Is it possible to get samsung phone working so that I can receive calls on my pc?

**Comment by Den4enko** [comment]
I've already asked about it #7 . Sadly; it's not possible now

**Comment by Bananz0** [comment]
No, I had found a way to but they blocked it.

**Comment by Its-its** [comment]
As an alternative, the Microsoft "Phone Link" Program works great for this. I've never had issues as of yet. It works with all Android phones.
