### ISSUE TITLE
Quick Share and Multi Control is not working

### ISSUE THREAD

**Issue by The-DarkMatter** [Bananz0/GalaxyBookEnabler#15]
Hey thanks for making this utility. Unfortunately multi control and quick share doesn't list any device there. I have a Legion 5 pro fitted with Intel AX210 wifi card and a S23 ultra. Another app called "Quick Share by Google" (Google's Nearby share was renamed) is working fine for me. 
Can you please help me fix this issue on my PC?

**Comment by The-DarkMatter** [comment]
Hey, after restart and some half an hour. The multi-control magically worked! 
![image](https://github.com/user-attachments/assets/2c8c7944-319b-4a40-a8fc-fa5cb9846114)
Quick share is still not working, but I am happy with the other app I downloaded from Google. 
Thanks a lot!

**Comment by The-DarkMatter** [comment]
Hey again, it is not working. Please can you help me figure out what is wrong? Both are on same wifi, multi control is on on phone, battery saver is off.
![image](https://github.com/user-attachments/assets/bed16d13-4c48-44aa-b54b-840c50b90701)

**Comment by Bananz0** [comment]
I think this is just an issue with Samsung's implementation of the continuity services across different APs.  Are you using a combination of mesh connections where there's two wifi aps giving the same wifi name?
