### ISSUE TITLE
Powershell Version

### ISSUE THREAD

**Issue by SNAKEYE18** [Bananz0/GalaxyBookEnabler#2]
I spent the past hour scratching my head why I was not able to install the script. I would like to ask if you could add in the readme that you need powershell version 7 to run this program. I believe the version that shipped on my laptop was version 5, and I was getting all sorts of errors with that version. Installing the version 7.4.0 from the Microsoft store fixed all of my problems. Thank you for this awesome bypass, cant wait to install it on my framework when it arrives.

**Comment by Bananz0** [comment]
I'll add that in a few, thank you for pointing that out!
