### ISSUE TITLE
Clipboard sharing not working

### ISSUE THREAD

**Issue by maharshi18** [Bananz0/GalaxyBookEnabler#20]
I have tried this method and everything seems to work fine.

I was able to connect my S23U and Tab S9 with multi control.
Was able to seamlessly transfer my mouse and keyboard.

The only thing which annoys me is clipboard sharing. 
I have tried enabling "clipboard history across devices" in windows settings, but no luck.
And there were no option related to this i was able to find.

Is it working for everyone? Let me know if anything other information is required.

**Comment by Bananz0** [comment]
Clipboard sharing across devices also doesn't work well for me. As far as I know, you need to have multi control always on and connected to the device you want to share it with. Sometimes it won't work with my tab and phone without this hackaround and think that Samsung's implementation of clipboard sync is just horrendous.

**Comment by maharshi18** [comment]
@Bananz0 
Well, i never had the issue b/w S23 Ultra and Tab S9.
Anyway, i have started using phone link as well, so clipboard sync is working fine with that.
