### ISSUE TITLE
三星设置服务无法使用

### ISSUE THREAD

**Issue by WJTFeng** [Bananz0/GalaxyBookEnabler#21]
![1730649344380](https://github.com/user-attachments/assets/226bc3bd-1c1e-4ab2-91cd-8f9e71c7fc2c)
如图，首次安装使用时没有问题，但是当电脑重启过几次后便无法使用
此外，剪贴板共享功能只能由电脑向手机平板进行共享，无法从手机平板上共享到电脑，有什么解决方案吗

**Comment by Bananz0** [comment]
Could you go into Task Scheduler ( Start -> Task Scheculer -> Task Scheduler Library)  and check if it matches this? 
![image](https://github.com/user-attachments/assets/74d79324-374e-4e4e-ad23-e647deb675aa)

- Open start menu 
- Type "Task Scheduler"
- Go to Task Scheduler Library in the left-hand panel.
- Look for the task named GalaxyBookEnabler in the list.
- Double-click the task to open its properties and verify the following:

For the clipboard issue, please see #20
