### ISSUE TITLE
Line 200 '||' token is invalid

### ISSUE THREAD

**Issue by vink2212** [Bananz0/GalaxyBookEnabler#3]
Tried to run the script on my machine but was unable to. Kept running into the error shown below 
<img width="444" alt="image" src="https://github.com/Bananz0/GalaxyBookEnabler/assets/62817618/fe0fe629-0b82-43b5-9854-6c879de71ead">

I was able to fix it by changing || to -or.

**Comment by vink2212** [comment]
Another issue I am facing is that after using this script, Samsung continuity service is just broken. It won't start and won't open no matter what. Tried re-installing it in every possible way but nothing worked. In MS store the app does not even show the open button. Multi control works fine tho, i can use my mouse and keyboard on the other device but i cannot copy on one device and have it paste on another.

**Comment by Bananz0** [comment]
> Tried to run the script on my machine but was unable to. Kept running into the error shown below <img alt="image" width="444" src="https://private-user-images.githubusercontent.com/62817618/284975557-fe0fe629-0b82-43b5-9854-6c879de71ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDE2OTMsIm5iZiI6MTcwMTEwMTM5MywicGF0aCI6Ii82MjgxNzYxOC8yODQ5NzU1NTctZmUwZmU2MjktMGI4Mi00M2I1LTk4NTQtNmM4NzlkZTcxZWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2MDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNTk3YjM4NTQ5MTJlM2M4OTY2MDRjN2FhMTY2YjlkM2I5NjY2MDQyMDYxMWU3NjUxOGUzNWU3ZDk1ZDljMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFIp-ZRpUdpJv_e2_zBNAc-W0VazayudjbNg1Tm9nck">
> 
> I was able to fix it by changing || to -or.

This may be because of a difference in the PowerShell version being used. I was using PowerShell v7 for this, and it appears that the logical operators && and || among others were introduced in v7 and are not present in v5. I will check for other compatibility issues.

**Comment by vink2212** [comment]
Yeah, i think it was cause of that, but the thing is I used the command you posted to grab the latest powershell. Very weird, but could be the install was bonked somehow. Another (and now bigger) issue I have is that Samsung's continuity service just refuses to work. It worked for a day once and now has just fully stopped. I can use multi control but i can use the copy and paste feature between laptop and phone.

**Comment by Bananz0** [comment]
I also cannot launch the continuity service on my laptop, I think it needs another app to launch it, possibly Samsung Settings that I cannot get to work.
