### ISSUE TITLE
please update for compatibility to one UI 6.0

### ISSUE THREAD

**Issue by MrBaggins24** [Bananz0/GalaxyBookEnabler#4]
Great script however the ids for the program packages I believe are outdated now that Samsung has released one UI 6.0

**Comment by vink2212** [comment]
Yeah some of the newer versions of the windows Samsung apps also do not work correctly atm. @Bananz0 hope you can work on this when you get the time.

**Comment by Bananz0** [comment]
Let me have a look at it right now, I've been away for some time @vink2212

**Comment by MrBaggins24** [comment]
Thank you

**Comment by Bananz0** [comment]
> Great script however the ids for the program packages I believe are outdated now that Samsung has released one UI 6.0

I believe that the links are still the same, correct me if I'm wrong, as I am able to install the packages as of the time of writing this
