### ISSUE TITLE
Quick Share not working.

### ISSUE THREAD

**Issue by AymanAliS** [Bananz0/GalaxyBookEnabler#6]
Followed the steps and downloaded everything from the given links and while Samsung Notes and Multi Control are working perfectly, Quick Share after about 5 or so seconds gives me "Quick Share isn't compatible with this computer." pop up and forces me to close the app.

<img width="528" alt="image" src="https://github.com/Bananz0/GalaxyBookEnabler/assets/100697953/ef941095-b136-485b-8f74-214580af2b83">
<img width="350" alt="image" src="https://github.com/Bananz0/GalaxyBookEnabler/assets/100697953/99e97151-2a5e-4dcd-817a-ea0b2f37df59">

**Comment by Bananz0** [comment]
That could be because of your Wi-Fi card, could you confirm if you have an intel or killer wifi card?

**Comment by SurajBhari** [comment]
hey i have the same thing. 
for me the wi-fi card is `Realtek RTL8852AE`

**Comment by Bananz0** [comment]
Unfortunately, it seems an update added a check for Intel/Killer internet cards, causing compatibility issues with others. The only fix for now is to use an older version, but finding the installer might be tough. Sorry for the inconvenience!
