### ISSUE TITLE
Fix support for Samsung Phone app

### ISSUE THREAD

**Issue by Den4enko** [Bananz0/GalaxyBookEnabler#7]
Hello! I like how this script works with other Samsung's apps. But there is a new SamsungPhone app, which helps to make and receive calls on PC. Sadly, it says, that device is not supported. [Link to app on Microsoft Store](https://apps.microsoft.com/detail/9MWJXXLCHBGK?hl=en-US&gl=US)
![image](https://github.com/Bananz0/GalaxyBookEnabler/assets/60628208/ee682a23-627b-48d6-886c-1300db01c713)

**Comment by Bananz0** [comment]
Unfortunately I don't think this is possible as they have changed the way to check for the model number, and instead of using registry, they use the WMI which afaik is read-only as per the Microsoft spec. Any help would be appreciated though

**Comment by Bananz0** [comment]
They are checking for values in the BIOS for this. There's no apparent way to fix this without hardware hacking. I have tried it and it seems they are also working on patching that (with Bixby). Sadly seems that this may also stop working soon

**Comment by wxxsfxyzm** [comment]
I have an idea: Use a custom bootloader to fake the information of bios，such as opencore？could you tell me which key exactly bixby reads, so that I can test it

**Comment by Bananz0** [comment]
I did that, worked for some time and they added another check after the
initial check. It does bypass some other apps but has the disadvantage of
making some of your OEM apps not work.
